services:
    mysql:
        image: mysql:8.0
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-examplepassword}
            MYSQL_DATABASE: ${DB_DATABASE:-inventory_management_system}
            MYSQL_USER: ${DB_USERNAME:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-examplepassword}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE:-inventory_management_system}
            - DB_USERNAME=${DB_USERNAME:-root}
            - DB_PASSWORD=${DB_PASSWORD:-examplepassword}
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        networks:
            - laravel_network
        command: >
            bash -c "
                php artisan migrate --force &&
                php artisan storage:link &&
                php artisan serve --host=0.0.0.0 --port=8000
            "

volumes:
    mysql_data:

networks:
    laravel_network:
        driver: bridge
